{{- $appName := include "helm.appName" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{$appName}}-{{.Release.Name}}-api-service
  labels:
    app: {{$appName}}-{{.Release.Name}}
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: {{$appName}}-{{.Release.Name}}
    tier: api
