version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.6.1
  node: circleci/node@1.1.6
  helm: circleci/helm@0.2.3
jobs:
  test-and-coverage:
    working_directory: ~/tracks/backend
    executor:
      name: "node/default"
    steps:
      - checkout:
          path: ~/tracks
      - node/with-cache:
          steps:
            - run: yarn
            - run: yarn run test
            - run: yarn run test:cov
  lint:
    working_directory: ~/tracks/backend
    executor:
      name: "node/default"
    steps:
      - checkout:
          path: ~/tracks
      - node/with-cache:
          steps:
            - run: yarn
            - run: yarn run lint
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: Setup Google Cloud SDK
          command: |
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json

            # Initialize gcloud CLI
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project $GOOGLE_PROJECT_ID
            gcloud --quiet config set compute/zone $GOOGLE_COMPUTE_ZONE
            gcloud --quiet container clusters get-credentials $GOOGLE_CLUSTER_NAME
            gcloud --quiet --verbosity=none compute disks create ${CIRCLE_BRANCH}-pg-data-disk --size 5GB --zone europe-west1-b
      - setup_remote_docker
      - helm/install-helm-chart:
          chart: ~/project/helm
          release-name: ${CIRCLE_BRANCH}
          namespace: ${CIRCLE_BRANCH}

workflows:
  build-test-lint:
    jobs:
      - test-and-coverage
      - lint
      - gcp-gcr/build-and-push-image:
          dockerfile: backend/Dockerfile
          image: backend
          tag: ${CIRCLE_BRANCH}
          path: ~/project/backend
          requires:
            - lint
            - test-and-coverage
      - deploy_to_staging:
          requires:
            - gcp-gcr/build-and-push-image
