apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tracks
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: tracks
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tracks
        tier: backend
    spec:
      containers:
        - image: gcr.io/tracks-274321/backend:master
          name: backend
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: backend-deploy
