{{- $appName := include "helm.appName" . -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{$appName}}-{{.Release.Name}}-frontend-ingress
spec:
  rules:
  - host: {{.Release.Name}}.tracks.social
    http:
      paths:
      - path: /
        backend:
          serviceName: {{$appName}}-{{.Release.Name}}-frontend-service
          servicePort: 80
